package cassandraTables

import "github.com/scylladb/gocqlx/v2/table"

var advEventMetadata = table.Metadata{
	Name: "MLDatabase.advEventModels",
	Columns: []string{
		"project_id",
		"client_id",
		"customer_id",
		"level_index",
		"total_adv_day",
		"total_adv_count",
		"total_adv_hour",
		"total_adv_minute",
		"level_based_average_adv_count",
		"average_adv_daily_click_count",
		"first_adv_year_of_day",
		"first_adv_year",
		"first_week_day",
		"first_adv_click_hour",
		"first_adv_click_minute",
		"first_adv_type",
		"second_adv_year_of_day",
		"second_adv_hour",
		"second_adv_minute",
		"second_adv_type",
		"third_adv_year_of_day",
		"third_adv_hour",
		"third_adv_minute",
		"third_adv_type",
		"fourth_adv_year_of_day",
		"fourth_adv_hour",
		"fourth_adv_minute",
		"fourth_adv_type",
		"fifth_adv_year_of_day",
		"fifth_adv_hour",
		"fifth_adv_minute",
		"fifth_adv_type",
		"penultimate_adv_year_of_day",
		"penultimate_adv_hour",
		"penultimate_adv_minute",
		"penultimate_adv_type",
		"last_adv_year_of_day",
		"last_adv_year",
		"last_adv_click_hour",
		"last_adv_click_minute",
		"last_adv_type",
		"first_half_hour_adv_click_count",
		"first_hour_adv_click_count",
		"first_two_hour_adv_click_count",
		"firs_three_hour_adv_click_count",
		"first_six_hour_adv_click_count",
		"first_twelve_hour_adv_click_count",
		"first_day_adv_click_count",
		"second_day_adv_click_count",
		"third_day_adv_click_count",
		"fourth_day_adv_click_count",
		"fifth_day_adv_click_count",
		"sixth_day_adv_click_count",
		"seventh_day_adv_click_count",
		"penultimate_day_adv_click_count",
		"last_day_adv_click_count",
		"last_minus_first_day_adv_click_count",
		"last_minus_penultimate_day_adv_click_count",
		"last_day_adv_click_count_minus_average_daily_adv_click_count",
		"sunday_adv_click_count",
		"monday_adv_click_count",
		"tuesday_adv_click_count",
		"wednesday_adv_click_count",
		"thursday_adv_click_count",
		"friday_adv_click_count",
		"saturday_adv_click_count",
		"am_adv_click_count",
		"pm_adv_click_count",
		"adv_click_0_to_5_hour_count",
		"adv_click_6_to_11_hour_count",
		"adv_click_12_to_17_hour_count",
		"adv_click_18_to_23_hour_count",
	},
	PartKey: []string{"project_id"},
	SortKey: []string{"client_id"},
}

var AdvEventTable = table.New(advEventMetadata)
