package cassandraTables

import "github.com/scylladb/gocqlx/v2/table"

var buyingEventMetadata = table.Metadata{
	Name: "MLDatabase.buyingEventModels",
	Columns: []string{
		"project_id",
		"client_id",
		"customer_id",
		"level_index",
		"total_buying_count",
		"total_buying_day",
		"total_buying_hour",
		"first_buying_year_of_day",
		"first_buying_year",
		"first_buying_hour",
		"first_buying_minute",
		"first_buying_product_type",
		"second_buying_year_of_day",
		"second_buying_hour",
		"second_buying_minute",
		"second_buying_product_type",
		"third_buying_year_of_day",
		"third_buying_hour",
		"third_buying_minute",
		"third_buying_product_type",
		"fourth_buying_year_of_day",
		"fourth_buying_hour",
		"fourth_buying_minute",
		"fourth_buying_product_type",
		"fifth_buying_year_of_day",
		"fifth_buying_hour",
		"fifth_buying_minute",
		"fifth_buying_product_type",
		"penultimate_buying_year_of_day",
		"penultimate_buying_hour",
		"penultimate_buying_minute",
		"penultimate_buying_product_type",
		"last_buying_year_of_day",
		"last_buying_year",
		"last_buying_hour",
		"last_buying_minute",
		"last_buying_product_type",
		"first_day_buying_count",
		"second_day_buying_count",
		"third_day_buying_count",
		"fourth_day_buying_count",
		"fifth_day_buying_count",
		"sixth_day_buying_count",
		"seventh_day_buying_count",
		"sunday_buying_count",
		"monday_buying_count",
		"tuesday_buying_count",
		"wednesday_buying_count",
		"thursday_buying_count",
		"friday_buying_count",
		"saturday_buying_count",
		"am_buying_count",
		"pm_buying_count",
		"buying_0_to_5_hour_count",
		"buying_6_to_11_hour_count",
		"buying_12_to_17_hour_count",
		"buying_18_to_23_hour_count",
		"buying_day_average_buying_count",
		"level_based_average_buying_count",
	},
	PartKey: []string{"project_id"},
	SortKey: []string{"client_id"},
}

var BuyingEventTable = table.New(buyingEventMetadata)
