package cassandraTables

import "github.com/scylladb/gocqlx/v2/table"

var gameSessionMetadata = table.Metadata{
	Name: "MLDatabase.gameSessionModels",
	Columns: []string{
		"project_id",
		"client_id",
		"customer_id",
		"first_session_year_of_day",
		"first_session_year",
		"first_session_week_day",
		"first_session_hour",
		"first_session_duration",
		"first_session_minute",
		"second_session_hour",
		"second_session_duration",
		"second_session_minute",
		"third_session_hour",
		"third_session_duration",
		"third_session_minute",
		"fourth_session_hour",
		"fourth_session_duration",
		"fourth_session_minute",
		"fifth_session_hour",
		"fifth_session_duration",
		"fifth_session_minute",
		"penultimate_session_hour",
		"penultimate_session_duration",
		"penultimate_session_minute",
		"last_session_year_of_day",
		"last_session_year",
		"last_session_hour",
		"last_session_duration",
		"last_session_minute",
		"last_duration_minus_penultimate_duration",
		"first_half_hour_total_session_count",
		"first_half_hour_total_session_duration",
		"first_hour_total_session_count",
		"first_hour_total_session_duration",
		"first_two_hour_total_session_count",
		"first_two_hour_total_session_duration",
		"first_three_hour_total_session_count",
		"first_three_hour_total_session_duration",
		"first_six_hour_total_session_count",
		"first_six_hour_total_session_duration",
		"first_twelve_hour_total_session_count",
		"first_twelve_hour_total_session_duration",
		"total_session_day",
		"total_session_hour",
		"total_session_minute",
		"total_session_duration",
		"total_session_count",
		"first_day_total_session_count",
		"first_day_total_session_duration",
		"second_day_total_session_count",
		"second_day_total_session_duration",
		"third_day_total_session_count",
		"third_day_total_session_duration",
		"fourth_day_total_session_count",
		"fourth_day_total_session_duration",
		"fifth_day_total_session_count",
		"fifth_day_total_session_duration",
		"sixth_day_total_session_count",
		"sixth_day_total_session_duration",
		"seventh_day_total_session_dount",                               
		"seventh_day_total_session_duration",                            
		"min_session_duration",                                        
		"max_session_duration",                                        
		"daily_avegare_session_count",                                  
		"daily_average_session_duration",                               
		"session_based_avegare_session_duration",                        
		"daily_avegare_session_count_minus_first_day_session_count",         
		"daily_avegare_session_duration_minus_first_day_session_duration",   
		"session_based_avegare_session_duration_minus_first_session_duration",
		"session_based_avegare_session_duration_minus_last_session_duration",
		"sunday_session_count",                                        
		"monday_session_count",                                        
		"tuesday_session_count",                                       
		"wednesday_session_count",                                     
		"thursday_session_count",                                      
		"friday_session_count",                                        
		"saturday_session_count",                                      
		"am_session_count",                                            
		"pm_session_count",                                            
		"session_0_to_5_hour_count",                                      
		"session_6_to_11_hour_count",                                      
		"session_12_to_17_hour_count",                                     
		"session_18_to_23_hour_count",
	},
	PartKey: []string{"project_id"},
	SortKey: []string{"client_id"},
}

var GameSessionTable = table.New(gameSessionMetadata)