package cassandraTables

import "github.com/scylladb/gocqlx/v2/table"

var levelBaseSessionMetadata = table.Metadata{
	Name: "MLDatabase.levelBaseSessionModels",
	Columns: []string{
		"project_id",
		"client_id",
		"customer_id",
		"total_level_base_session_minute",               
		"total_level_base_session_count",                
		"first_level_session_level_index",               
		"first_level_session_duration",                 
		"first_level_session_year_of_day",                
		"first_level_session_year",                     
		"first_level_session_week_day",                  
		"first_level_session_hour",                     
		"first_level_session_minute",                   
		"second_level_session_level_index",              
		"second_level_session_duration",                
		"third_level_session_level_index" ,              
		"third_level_session_duration",                 
		"four_level_session_level_index",                
		"four_level_session_duration",                  
		"five_level_session_level_index",                
		"five_level_session_duration",                  
		"six_level_session_level_index",                 
		"six_level_session_duration",                   
		"seven_level_session_level_index",               
		"seven_level_session_duration",                 
		"first_quarter_hour_total_level_base_session_count",
		"first_half_hour_total_level_base_session_count",   
		"first_hour_total_level_base_session_count" ,      
		"first_two_hour_total_level_base_session_count" ,   
		"first_three_hour_total_level_base_session_count" , 
		"first_six_hour_total_level_base_session_count",    
		"first_twelve_hour_total_level_base_session_count" ,
		"first_day_total_level_base_session_count" ,       
		"penultimate_level_session_level_index",         
		"penultimate_level_session_level_duration" ,     
		"last_level_session_level_index" ,               
		"last_level_session_level_duration" ,            
		"last_level_session_year_of_day",                 
		"last_level_session_year" ,                     
		"last_level_session_week_day",                   
		"last_level_session_hour",                      
		"last_level_session_minute" ,
	},
	PartKey: []string{"project_id"},
	SortKey: []string{"client_id"},
}

var LevelBaseSessionTable = table.New(levelBaseSessionMetadata)