package cassandraTables

import "github.com/scylladb/gocqlx/v2/table"

var screenClickMetadata = table.Metadata{
	Name: "MLDatabase.sessionClickModels",
	Columns: []string{
		"project_id",
		"client_id",
		"customer_id",
		"level_index",
		"first_click_session_year_of_day",
		"first_click_session_year",
		"first_click_session_hour",
		"first_click_session_minute",
		"first_touch_count",
		"second_click_session_hour",
		"second_click_session_minute",
		"second_touch_count",
		"third_click_session_hour",
		"third_click_session_minute",
		"third_touch_count",
		"fourth_click_session_hour",
		"fourth_click_session_minute",
		"fourth_touch_count",
		"fifth_click_session_hour",
		"fifth_click_session_minute",
		"fifth_touch_count",
		"penultimate_click_session_hour",
		"penultimate_click_session_minute",
		"penultimate_touch_count",
		"last_click_session_year_of_day",
		"last_click_session_year",
		"last_click_session_hour",
		"last_click_session_minute",
		"last_touch_count",
		"first_start_x_cor",
		"first_start_y_cor",
		"first_finish_x_cor",
		"first_finish_y_cor",
		"second_start_x_cor",
		"second_start_y_cor",
		"second_finish_x_cor",
		"second_finish_y_cor",
		"third_start_x_cor",
		"third_start_y_cor",
		"third_finish_x_cor",
		"third_finish_y_cor",
		"fourth_start_x_cor",
		"fourth_start_y_cor",
		"fourth_finish_x_cor",
		"fourth_finish_y_cor",
		"fifth_start_x_cor",
		"fifth_start_y_cor",
		"fifth_finish_x_cor",
		"fifth_finish_y_cor",
		"penultimate_start_x_Cor",
		"penultimate_start_y_cor",
		"penultimate_finish_x_cor",
		"penultimate_finish_y_cor",
		"last_start_x_cor",
		"last_start_y_cor",
		"last_finish_x_cor",
		"last_finish_y_cor",
		"first_half_hour_touch_count",
		"first_hour_touch_count",
		"first_two_hour_touch_count",
		"first_three_hour_touch_count",
		"first_six_hour_touch_count",
		"first_twelve_hour_touch_count",
		"first_minus_last_touch_count",
		"first_finger_id",
		"penultimate_finger_id",
		"last_finger_id",
		"first_day_click_count",
		"second_day_click_count",
		"third_day_click_count",
		"fourth_day_click_count",
		"fifth_day_click_count",
		"sixth_day_click_count",
		"seventh_day_click_count",
		"total_click_day",
		"total_click_count",
		"total_click_session_count",
		"total_click_hour",
		"total_click_minute",
		"total_start_x_cor",
		"total_start_y_cor",
		"total_finish_x_cor",
		"total_finish_y_cor",
		"session_based_avegare_start_x_cor",
		"session_based_avegare_start_y_cor",
		"session_based_avegare_finish_x_cor",
		"session_based_avegare_finish_y_cor",
		"session_based_avegare_click_count",
		"daily_avegare_click_count",
		"last_touch_count_minus_session_based_avegare_click_count",
	},
	PartKey: []string{"project_id"},
	SortKey: []string{"client_id"},
}

var ScreenClickTable = table.New(screenClickMetadata)
