package model

import "time"

type AdvEventRespondModel struct {
	ProjectId                                          string
	ClientId                                           string
	CustomerId                                         string
	LevelIndex                                         int16
	TotalAdvDay                                        int32
	TotalAdvCount                                      int32
	TotalAdvHour                                       int32
	TotalAdvMinute                                     int32
	LevelBasedAverageAdvCount                          float32
	AverageAdvDailyClickCount                          float32
	FirstAdvYearOfDay                                  int16
	FirstAdvYear                                       int16
	FirstWeekDay                                       int16
	FirstAdvClickHour                                  int16
	FirstADvClickMinute                                int16
	FirstAdvType                                       int16
	SecondAdvYearOfDay                                 int16
	SecondAdvHour                                      int16
	SecondAdvMinute                                    int16
	SecondAdvType                                      int16
	ThirdAdvYearOfDay                                  int16
	ThirdAdvHour                                       int16
	ThirdAdvMinute                                     int16
	ThirdAdvType                                       int16
	FourthAdvYearOfDay                                 int16
	FourthAdvHour                                      int16
	FourthAdvMinute                                    int16
	FourthAdvType                                      int16
	FifthAdvYearOfDay                                  int16
	FifthAdvHour                                       int16
	FifthAdvMinute                                     int16
	FifthAdvType                                       int16
	PenultimateAdvYearOfDay                            int16
	PenultimateAdvHour                                 int16
	PenultimateAdvMinute                               int16
	PenultimateAdvType                                 int16
	LastAdvYearOfDay                                   int16
	LastAdvYear                                        int16
	LastAdvClickHour                                   int16
	LastAdvClickMinute                                 int16
	LastAdvType                                        int16
	FirstHalfHourAdvClickCount                         int16
	FirstHourAdvClickCount                             int16
	FirstTwoHourAdvClickCount                          int16
	FirstThreeHourAdvClickCount                        int16
	FirstSixHourAdvClickCount                          int16
	FirstTwelveHourAdvClickCount                       int16
	FirstDayAdvClickCount                              int16
	SecondDayAdvClickCount                             int16
	ThirdDayAdvClickCount                              int16
	FourthDayAdvClickCount                             int16
	FifthDayAdvClickCount                              int16
	SixthDayAdvClickCount                              int16
	SeventhDayAdvClickCount                            int16
	PenultimateDayAdvClickCount                        int16
	LastDayAdvClickCount                               int16
	LastMinusFirstDayAdvClickCount                     int16
	LastMinusPenultimateDayAdvClickCount               int16
	LastDayAdvClickCountMinusAverageDailyAdvClickCount float32
	SundayAdvClickCount                                int16
	MondayAdvClickCount                                int16
	TuesdayAdvClickCount                               int16
	WednesdayAdvClickCount                             int16
	ThursdayAdvClickCount                              int16
	FridayAdvClickCount                                int16
	SaturdayAdvClickCount                              int16
	AmAdvClickCount                                    int16
	PmAdvClickCount                                    int16
	AdvClick0To5HourCount                              int16
	AdvClick6To11HourCount                             int16
	AdvClick12To17HourCount                            int16
	AdvClick18To23HourCount                            int16
}

//IsdeadAndVideoClickCount                                  int16

type AdvEventModel struct {
	ProjectId   string
	ClientId    string
	CustomerId  string
	LevelName   string
	LevelIndex  int
	AdvType     string
	InMinutes   int
	TrigerdTime time.Time
}
