package model

import "time"

type ScreenSwipeRespondModel struct {
	ProjectId              string
	ClientId               string
	CustomerId             string
	LevelIndex             int64
	TotalSwipeSessionCount int64
	TotalSwipeHour int64
	FirstSwipeYearOfDay int64
	FirstSwipeYear      int64
	FirstSwipeHour      int64
	FirstSwipeWeekDay int64
	FirstSwipeMinute  int64
	FistSwipeDirection    int64
	FirstSwipeStartXCor   float64
	FirstSwipeStartYCor   float64
	FirstSwipeFinishXCor  float64
	FirstSwipeFinishYCor  float64
	SecondSwipeDirection  int64
	SecondSwipeStartXCor  float64
	SecondSwipeStartYCor  float64
	SecondSwipeFinishXCor float64
	SecondSwipeFinishYCor float64
	ThirdSwipeDirection   int64
	ThirdSwipeStartXCor   float64
	ThirdSwipeStartYCor   float64
	ThirdSwipeFinishXCor  float64
	ThirdSwipeFinishYCor  float64
	FourthSwipeDirection  int64
	FourthSwipeStartXCor  float64
	FourthSwipeStartYCor  float64
	FourthSwipeFinishXCor float64
	FourthSwipeFinishYCor float64
	FifthSwipeDirection   int64
	FifthSwipeStartXCor   float64
	FifthSwipeStartYCor   float64
	FifthSwipeFinishXCor  float64
	FifthSwipeFinishYCor  float64
	PenultimateSwipeDirection  int64
	PenultimateSwipeStartXCor  float64
	PenultimateSwipeStartYCor  float64
	PenultimateSwipeFinishXCor float64
	PenultimateSwipeFinishYCor float64
	PenultimateSwipeYearOfDay int64
	PenultimateSwipeYear      int64
	PenultimateSwipeHour      int64
	PenultimateSwipeWeekDay   int64
	PenultimateSwipeMinute    int64
	LastSwipeDirection  int64
	LastSwipeStartXCor  float64
	LastSwipeStartYCor  float64
	LastSwipeFinishXCor float64
	LastSwipeFinishYCor float64
	LastSwipeYearOfDay int64
	LastSwipeYear      int64
	LastSwipeHour      int64
	LastSwipeWeekDay   int64
	LastSwipeMinute    int64
	FirstDayTotalSwipeUpCount    int64
	FirstDayTotalSwipeDownCount  int64
	FirstDayTotalSwipeRightCount int64
	FirstDayTotalSwipeLeftCount  int64
	FirstDaySwipeTotalStartXCor  float64
	FirstDaySwipeTotalStartYCor  float64
	FirstDaySwipeTotalFinishXCor float64
	FirstDaySwipeTotalFinishYCor float64
	SecondDayTotalSwipeUpCount    int64
	SecondDayTotalSwipeDownCount  int64
	SecondDayTotalSwipeRightCount int64
	SecondDayTotalSwipeLeftCount  int64
	SecondDaySwipeTotalStartXCor  float64
	SecondDaySwipeTotalStartYCor  float64
	SecondDaySwipeTotalFinishXCor float64
	SecondDaySwipeTotalFinishYCor float64
	ThirdDayTotalSwipeUpCount    int64
	ThirdDayTotalSwipeDownCount  int64
	ThirdDayTotalSwipeRightCount int64
	ThirdDayTotalSwipeLeftCount  int64
	ThirdDaySwipeTotalStartXCor  float64
	ThirdDaySwipeTotalStartYCor  float64
	ThirdDaySwipeTotalFinishXCor float64
	ThirdDaySwipeTotalFinishYCor float64
	FourthDayTotalSwipeUpCount    int64
	FourthDayTotalSwipeDownCount  int64
	FourthDayTotalSwipeRightCount int64
	FourthDayTotalSwipeLeftCount  int64
	FourthDaySwipeTotalStartXCor  float64
	FourthDaySwipeTotalStartYCor  float64
	FourthDaySwipeTotalFinishXCor float64
	FourthDaySwipeTotalFinishYCor float64
	FifthDayTotalSwipeUpCount    int64
	FifthDayTotalSwipeDownCount  int64
	FifthDayTotalSwipeRightCount int64
	FifthDayTotalSwipeLeftCount  int64
	FifthDaySwipeTotalStartXCor  float64
	FifthDaySwipeTotalStartYCor  float64
	FifthDaySwipeTotalFinishXCor float64
	FifthDaySwipeTotalFinishYCor float64
	SixthDayTotalSwipeUpCount    int64
	SixthDayTotalSwipeDownCount  int64
	SixthDayTotalSwipeRightCount int64
	SixthDayTotalSwipeLeftCount  int64
	SixthDaySwipeTotalStartXCor  float64
	SixthDaySwipeTotalStartYCor  float64
	SixthDaySwipeTotalFinishXCor float64
	SixthDaySwipeTotalFinishYCor float64
	SeventhDayTotalSwipeUpCount    int64
	SeventhDayTotalSwipeDownCount  int64
	SeventhDayTotalSwipeRightCount int64
	SeventhDayTotalSwipeLeftCount  int64
	SeventhDaySwipeTotalStartXCor  float64
	SeventhDaySwipeTotalStartYCor  float64
	SeventhDaySwipeTotalFinishXCor float64
	SeventhDaySwipeTotalFinishYCor float64
	TotalSwipeUpCount    int64
	TotalSwipeDownCount  int64
	TotalSwipeRightCount int64
	TotalSwipeLeftCount  int64
	TotalSwipeStartXCor  float64
	TotalSwipeStartYCor  float64
	TotalSwipeFinishXCor float64
	TotalSwipeFinishYCor float64
}

type ScreenSwipeModel struct {
	ProjectId       string
	ClientId        string
	CustomerId      string
	SwipeDirection  int
	SwipeStartXCor  float64
	SwipeStartYCor  float64
	SwipeFinishXCor float64
	SwipeFinishYCor float64
	CreationAt      time.Time
	LevelIndex      int
	LevelName       string
}
