package model

import "time"

type ScreenClickRespondModel struct {
	ProjectId                                        string
	ClientId                                         string
	CustomerId                                       string
	LevelIndex                                       int64
	FirstClickSessionYearOfDay                       int64
	FirstClickSessionYear                            int64
	FirstClickSessionHour                            int64
	FirstClickSessionMinute                          int64
	FirstTouchCount                                  int64
	SecondClickSessionHour                           int64
	SecondClickSessionMinute                         int64
	SecondTouchCount                                 int64
	ThirdClickSessionHour                            int64
	ThirdClickSessionMinute                          int64
	ThirdTouchCount                                  int64
	FourthClickSessionHour                           int64
	FourthClickSessionMinute                         int64
	FourthTouchCount                                 int64
	FifthClickSessionHour                            int64
	FifthClickSessionMinute                          int64
	FifthTouchCount                                  int64
	PenultimateClickSessionHour                      int64
	PenultimateClickSessionMinute                    int64
	PenultimateTouchCount                            int64
	LastClickSessionYearOfDay                        int64
	LastClickSessionYear                             int64
	LastClickSessionHour                             int64
	LastClickSessionMinute                           int64
	LastTouchCount                                   int64
	FirstStartXCor                                   float64
	FirstStartYCor                                   float64
	FirstFinishXCor                                  float64
	FirstFinishYCor                                  float64
	SecondStartXCor                                  float64
	SecondStartYCor                                  float64
	SecondFinishXCor                                 float64
	SecondFinishYCor                                 float64
	ThirdStartXCor                                   float64
	ThirdStartYCor                                   float64
	ThirdFinishXCor                                  float64
	ThirdFinishYCor                                  float64
	FourthStartXCor                                  float64
	FourthStartYCor                                  float64
	FourthFinishXCor                                 float64
	FourthFinishYCor                                 float64
	FifthStartXCor                                   float64
	FifthStartYCor                                   float64
	FifthFinishXCor                                  float64
	FifthFinishYCor                                  float64
	PenultimateStartXCor                             float64
	PenultimateStartYCor                             float64
	PenultimateFinishXCor                            float64
	PenultimateFinishYCor                            float64
	LastStartXCor                                    float64
	LastStartYCor                                    float64
	LastFinishXCor                                   float64
	LastFinishYCor                                   float64
	FirstHalfHourTouchCount                          int64
	FirstHourTouchCount                              int64
	FirstTwoHourTouchCount                           int64
	FirstThreeHourTouchCount                         int64
	FirstSixHourTouchCount                           int64
	FirstTwelveHourTouchCount                        int64
	FirstMinusLastTouchCount                         int64
	FirstFingerId                                    int64
	PenultimateFingerId                              int64
	LastFingerId                                     int64
	FirstDayClickCount                               int64
	SecondDayClickCount                              int64
	ThirdDayClickCount                               int64
	FourthDayClickCount                              int64
	FifthDayClickCount                               int64
	SixthDayClickCount                               int64
	SeventhDayClickCount                             int64
	TotalClickDay                                    int64
	TotalClickCount                                  int64
	TotalClickSessionCount                           int64
	TotalClickHour                                   int64
	TotalClickMinute                                 int64
	TotalStartXCor                                   float64
	TotalStartYCor                                   float64
	TotalFinishXCor                                  float64
	TotalFinishYCor                                  float64
	SessionBasedAvegareStartXCor                     float64
	SessionBasedAvegareStartYCor                     float64
	SessionBasedAvegareFinishXCor                    float64
	SessionBasedAvegareFinishYCor                    float64
	SessionBasedAvegareClickCount                    float64
	DailyAvegareClickCount                           float64
	LastTouchCountMinusSessionBasedAvegareClickCount float64
}

type ScreenClickModel struct {
	ProjectId  string
	ClientId   string
	CustomerId string
	StartXCor  float64
	StartYCor  float64
	FinishXCor float64
	FinishYCor float64
	TouchCount int
	FingerId   int
	LevelIndex int
	LevelName  string
	CreationAt time.Time
}
