package model

import "time"

type ScreenClickResponseModel struct {
	Id                                               int64
	ClientId                                         int64
	ProjectId                                        int64
	CustomerId                                       int64
	LevelIndex                                       int16
	FirstClickSessionYearOfDay                       int16
	FirstClickSessionYear                            int16
	FirstClickSessionHour                            int16
	FirstClickSessionMinute                          int16
	FirstTouchCount                                  int16
	SecondClickSessionHour                           int16
	SecondClickSessionMinute                         int16
	SecondTouchCount                                 int16
	ThirdClickSessionHour                            int16
	ThirdClickSessionMinute                          int16
	ThirdTouchCount                                  int16
	FourthClickSessionHour                           int16
	FourthClickSessionMinute                         int16
	FourthTouchCount                                 int16
	FifthClickSessionHour                            int16
	FifthClickSessionMinute                          int16
	FifthTouchCount                                  int16
	SixthClickSessionHour                            int16
	SixthClickSessionMinute                          int16
	SixthTouchCount                                  int16
	SeventhClickSessionHour                          int16
	SeventhClickSessionMinute                        int16
	SeventhTouchCount                                int16
	PenultimateClickSessionHour                      int16
	PenultimateClickSessionMinute                    int16
	PenultimateTouchCount                            int16
	LastClickSessionYearOfDay                        int16
	LastClickSessionYear                             int16
	LastClickSessionHour                             int16
	LastClickSessionMinute                           int16
	LastTouchCount                                   int16
	FirstStartXCor                                   float32
	FirstStartYCor                                   float32
	FirstFinishXCor                                  float32
	FirstFinishYCor                                  float32
	SecondStartXCor                                  float32
	SecondStartYCor                                  float32
	SecondFinishXCor                                 float32
	SecondFinishYCor                                 float32
	ThirdStartXCor                                   float32
	ThirdStartYCor                                   float32
	ThirdFinishXCor                                  float32
	ThirdFinishYCor                                  float32
	FourthStartXCor                                  float32
	FourthStartYCor                                  float32
	FourthFinishXCor                                 float32
	FourthFinishYCor                                 float32
	FifthStartXCor                                   float32
	FifthStartYCor                                   float32
	FifthFinishXCor                                  float32
	FifthFinishYCor                                  float32
	SixthStartXCor                                   float32
	SixthStartYCor                                   float32
	SixthFinishXCor                                  float32
	SixthFinishYCor                                  float32
	SeventhStartXCor                                 float32
	SeventhStartYCor                                 float32
	SeventhFinishXCor                                float32
	SeventhFinishYCor                                float32
	PenultimateStartXCor                             float32
	PenultimateStartYCor                             float32
	PenultimateFinishXCor                            float32
	PenultimateFinishYCor                            float32
	LastStartXCor                                    float32
	LastStartYCor                                    float32
	LastFinishXCor                                   float32
	LastFinishYCor                                   float32
	FirstFiveMinutesTouchCount                       int32
	FirstTenMinutesTouchCount                        int32
	FirstQuarterHourTouchCount                       int32
	FirstHalfHourTouchCount                          int32
	FirstHourTouchCount                              int32
	FirstTwoHourTouchCount                           int32
	FirstThreeHourTouchCount                         int32
	FirstSixHourTouchCount                           int32
	FirstTwelveHourTouchCount                        int32
	FirstMinusLastTouchCount                         int16
	FirstFingerId                                    byte
	PenultimateFingerId                              byte
	LastFingerId                                     byte
	FirstDayClickCount                               int32
	SecondDayClickCount                              int32
	ThirdDayClickCount                               int32
	FourthDayClickCount                              int32
	FifthDayClickCount                               int32
	SixthDayClickCount                               int32
	SeventhDayClickCount                             int32
	TotalClickDay                                    int32
	TotalClickCount                                  int32
	TotalClickSessionCount                           int32
	TotalClickHour                                   int32
	TotalClickMinute                                 int32
	TotalStartXCor                                   float32
	TotalStartYCor                                   float32
	TotalFinishXCor                                  float32
	TotalFinishYCor                                  float32
	SessionBasedAvegareStartXCor                     float32
	SessionBasedAvegareStartYCor                     float32
	SessionBasedAvegareFinishXCor                    float32
	SessionBasedAvegareFinishYCor                    float32
	SessionBasedAvegareClickCount                    float32
	DailyAvegareClickCount                           float32
	LastTouchCountMinusSessionBasedAvegareClickCount float32
	Status                                           bool
}

type ScreenClickModel struct {
	Id         int64
	ClientId   int64
	ProjectId  int64
	CustomerId int64
	StartLocX  float32
	StartLocY  float32
	FinishLocX float32
	FinishLocY float32
	LevelName  string
	LevelIndex int
	TabCount   int
	FingerId   int
	CreatedAt  time.Time
	Status     bool
}
